// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240208161146_Hide_Number_property_from_database")]
    partial class Hide_Number_property_from_database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("BaggageTagsSequence")
                .HasMax(999999L)
                .IsCyclic();

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaggageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationId")
                        .HasColumnType("text");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Baggage");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DividerPlacedBehindRow")
                        .HasColumnType("integer");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScheduledFlightId")
                        .HasColumnType("text");

                    b.Property<int>("TotalBookedPassengers")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCheckedBaggage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ScheduledFlightId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.Property<string>("RegistrationCode")
                        .HasColumnType("text");

                    b.Property<string>("AircraftTypeId")
                        .HasColumnType("text");

                    b.Property<string>("AirlineId")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.Property<int>("JumpSeatsAvailable")
                        .HasColumnType("integer");

                    b.Property<string>("SeatMapId")
                        .HasColumnType("text");

                    b.HasKey("RegistrationCode");

                    b.HasIndex("AircraftTypeId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("CountryId");

                    b.HasIndex("SeatMapId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.AircraftType", b =>
                {
                    b.Property<string>("AircraftTypeIATACode")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.HasKey("AircraftTypeIATACode");

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Airline", b =>
                {
                    b.Property<string>("CarrierCode")
                        .HasColumnType("text");

                    b.Property<int?>("AccountingCode")
                        .HasColumnType("integer");

                    b.Property<string>("AirlinePrefix")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CarrierCode");

                    b.HasIndex("CountryId");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.Property<string>("IATAAirportCode")
                        .HasColumnType("text");

                    b.Property<string>("AirportName")
                        .HasColumnType("text");

                    b.Property<string>("CountryId")
                        .HasColumnType("text");

                    b.HasKey("IATAAirportCode");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightBaggage", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<Guid>("BaggageId")
                        .HasColumnType("uuid");

                    b.HasKey("FlightId", "BaggageId");

                    b.HasIndex("BaggageId");

                    b.ToTable("FlightBaggage");
                });

            modelBuilder.Entity("Core.FlightContext.ScheduledFlight", b =>
                {
                    b.Property<string>("FlightNumber")
                        .HasColumnType("text");

                    b.Property<string>("AirlineId")
                        .HasColumnType("text");

                    b.Property<string>("ArrivalTimes")
                        .HasColumnType("jsonb");

                    b.Property<string[]>("Codeshare")
                        .HasColumnType("text[]");

                    b.Property<string>("DepartureTimes")
                        .HasColumnType("jsonb");

                    b.Property<string>("DestinationFromId")
                        .HasColumnType("text");

                    b.Property<string>("DestinationToId")
                        .HasColumnType("text");

                    b.Property<string>("FlightDuration")
                        .HasColumnType("jsonb");

                    b.HasKey("FlightNumber");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationFromId");

                    b.HasIndex("DestinationToId");

                    b.ToTable("ScheduledFlights");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.BookingReference", b =>
                {
                    b.Property<string>("PNR")
                        .HasColumnType("text");

                    b.Property<string>("FlightItinerary")
                        .HasColumnType("jsonb")
                        .HasColumnName("FlightItinerary");

                    b.HasKey("PNR");

                    b.ToTable("BookingReferences");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsMarkedAsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PredefinedCommentId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("PredefinedCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.FrequentFlyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirlineId")
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardholderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrequentFlyerNumber")
                        .HasColumnType("text");

                    b.Property<long>("MilesAvailable")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PassengerInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TierLever")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("PassengerInfoId")
                        .IsUnique();

                    b.ToTable("FrequentFlyers");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.PredefinedComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PredefinedComments");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.SSRCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsFreeTextMandatory")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.ToTable("SSRCodes");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.SpecialServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<string>("FreeText")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SSRCodeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SSRCodeId");

                    b.ToTable("SpecialServiceRequests");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerFlight", b =>
                {
                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<string>("AcceptanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BoardingSequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BoardingZone")
                        .HasColumnType("text");

                    b.HasKey("PassengerId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("PassengerFlight");
                });

            modelBuilder.Entity("Core.PassengerContext.PassengerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("BaggageAllowance")
                        .HasColumnType("integer");

                    b.Property<string>("BookedSSR")
                        .HasColumnType("jsonb")
                        .HasColumnName("BookedSSR");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FrequentFlyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PNRId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PriorityBoarding")
                        .HasColumnType("boolean");

                    b.Property<string>("ReservedSeats")
                        .HasColumnType("jsonb")
                        .HasColumnName("ReservedSeats");

                    b.HasKey("Id");

                    b.HasIndex("PNRId");

                    b.ToTable("PassengerInfo");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Core.PassengerContext.Regulatory.APISData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateOfIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueCountryId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalityId")
                        .HasColumnType("text");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueCountryId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PassengerId");

                    b.ToTable("APISData");
                });

            modelBuilder.Entity("Core.PassengerContext.Regulatory.Country", b =>
                {
                    b.Property<string>("Country2LetterCode")
                        .HasColumnType("text");

                    b.Property<string[]>("AircraftRegistrationPrefix")
                        .HasColumnType("text[]");

                    b.Property<string>("Country3LetterCode")
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEUCountry")
                        .HasColumnType("boolean");

                    b.HasKey("Country2LetterCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Core.SeatingContext.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FlightClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text");

                    b.Property<string>("SeatStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Core.SeatingContext.SeatMap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FlightClassesSpecification")
                        .HasColumnType("jsonb")
                        .HasColumnName("FlightClassesSpecification");

                    b.HasKey("Id");

                    b.ToTable("SeatMaps");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.HasBaseType("Core.PassengerContext.PassengerInfo");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "FinalDestination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("PassengerCheckedBags")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Core.BaggageContext.BaggageTag", "BaggageTag", b1 =>
                        {
                            b1.Property<Guid>("BaggageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TagNumber")
                                .HasColumnType("text")
                                .HasColumnName("TagNumber");

                            b1.HasKey("BaggageId");

                            b1.ToTable("Baggage");

                            b1.WithOwner()
                                .HasForeignKey("BaggageId");
                        });

                    b.OwnsOne("Core.BaggageContext.SpecialBag", "SpecialBag", b1 =>
                        {
                            b1.Property<Guid>("BaggageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SpecialBagDescription")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("SpecialBagDescription");

                            b1.Property<string>("SpecialBagType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SpecialBagType");

                            b1.HasKey("BaggageId");

                            b1.ToTable("Baggage");

                            b1.WithOwner()
                                .HasForeignKey("BaggageId");
                        });

                    b.Navigation("BaggageTag");

                    b.Navigation("FinalDestination");

                    b.Navigation("Passenger");

                    b.Navigation("SpecialBag");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId");

                    b.HasOne("Core.FlightContext.ScheduledFlight", "ScheduledFlight")
                        .WithMany()
                        .HasForeignKey("ScheduledFlightId");

                    b.OwnsOne("Core.BoardingContext.Boarding", "Boarding", b1 =>
                        {
                            b1.Property<int>("FlightId")
                                .HasColumnType("integer");

                            b1.Property<string>("BoardingStatus")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BoardingStatus");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.Navigation("Aircraft");

                    b.Navigation("Boarding");

                    b.Navigation("ScheduledFlight");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.AircraftType", "AircraftType")
                        .WithMany()
                        .HasForeignKey("AircraftTypeId");

                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany("Fleet")
                        .HasForeignKey("AirlineId");

                    b.HasOne("Core.PassengerContext.Regulatory.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Core.SeatingContext.SeatMap", "SeatMap")
                        .WithMany()
                        .HasForeignKey("SeatMapId");

                    b.Navigation("AircraftType");

                    b.Navigation("Airline");

                    b.Navigation("Country");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Airline", b =>
                {
                    b.HasOne("Core.PassengerContext.Regulatory.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.HasOne("Core.PassengerContext.Regulatory.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightBaggage", b =>
                {
                    b.HasOne("Core.BaggageContext.Baggage", "Baggage")
                        .WithMany("Flights")
                        .HasForeignKey("BaggageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("ListOfCheckedBaggage")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baggage");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Core.FlightContext.ScheduledFlight", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "DestinationFrom")
                        .WithMany("Departures")
                        .HasForeignKey("DestinationFromId");

                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "DestinationTo")
                        .WithMany("Arrivals")
                        .HasForeignKey("DestinationToId");

                    b.Navigation("Airline");

                    b.Navigation("DestinationFrom");

                    b.Navigation("DestinationTo");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.Comment", b =>
                {
                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("Comments")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Booking.PredefinedComment", "PredefinedComment")
                        .WithMany()
                        .HasForeignKey("PredefinedCommentId");

                    b.Navigation("Passenger");

                    b.Navigation("PredefinedComment");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.FrequentFlyer", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.PassengerInfo", "PassengerInfo")
                        .WithOne("FrequentFlyer")
                        .HasForeignKey("Core.PassengerContext.Booking.FrequentFlyer", "PassengerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("PassengerInfo");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.SpecialServiceRequest", b =>
                {
                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("SpecialServiceRequests")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Booking.SSRCode", "SSRCode")
                        .WithMany()
                        .HasForeignKey("SSRCodeId");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");

                    b.Navigation("SSRCode");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerFlight", b =>
                {
                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("ListOfBookedPassengers")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("Flights")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.PassengerContext.PassengerInfo", b =>
                {
                    b.HasOne("Core.PassengerContext.Booking.BookingReference", "PNR")
                        .WithMany("LinkedPassengers")
                        .HasForeignKey("PNRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PNR");
                });

            modelBuilder.Entity("Core.PassengerContext.Regulatory.APISData", b =>
                {
                    b.HasOne("Core.PassengerContext.Regulatory.Country", "IssueCountry")
                        .WithMany()
                        .HasForeignKey("IssueCountryId");

                    b.HasOne("Core.PassengerContext.Regulatory.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId");

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueCountry");

                    b.Navigation("Nationality");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.SeatingContext.Seat", b =>
                {
                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("AssignedSeats")
                        .HasForeignKey("PassengerId");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.HasOne("Core.PassengerContext.PassengerInfo", null)
                        .WithOne()
                        .HasForeignKey("Core.PassengerContext.Passenger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.Navigation("ListOfBookedPassengers");

                    b.Navigation("ListOfCheckedBaggage");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Airline", b =>
                {
                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.Navigation("Arrivals");

                    b.Navigation("Departures");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.BookingReference", b =>
                {
                    b.Navigation("LinkedPassengers");
                });

            modelBuilder.Entity("Core.PassengerContext.PassengerInfo", b =>
                {
                    b.Navigation("FrequentFlyer");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.Navigation("AssignedSeats");

                    b.Navigation("Comments");

                    b.Navigation("Flights");

                    b.Navigation("PassengerCheckedBags");

                    b.Navigation("SpecialServiceRequests");

                    b.Navigation("TravelDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
