// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230828215941_Rename_Countries_Properties")]
    partial class Rename_Countries_Properties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaggageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecialBag")
                        .HasColumnType("boolean");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialBagId")
                        .HasColumnType("integer");

                    b.Property<int>("TagNumberId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SpecialBagId");

                    b.HasIndex("TagNumberId")
                        .IsUnique();

                    b.ToTable("Baggage");
                });

            modelBuilder.Entity("Core.BaggageContext.SpecialBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDescriptionRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("SpecialBagDescription")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SpecialBagType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpecialBags");
                });

            modelBuilder.Entity("Core.BaggageContext.TagNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirlineCode")
                        .HasColumnType("text");

                    b.Property<int>("BagTagIssuerCode")
                        .HasColumnType("integer");

                    b.Property<int>("BaggageId")
                        .HasColumnType("integer");

                    b.Property<byte>("LeadingDigit")
                        .HasColumnType("smallint");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TagNumbers");
                });

            modelBuilder.Entity("Core.BoardingContext.Boarding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.ToTable("Boarding");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<int>("AirlineId")
                        .HasColumnType("integer");

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("integer");

                    b.Property<string>("ArrivalDateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BoardingId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureDateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("integer");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlightType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftRegistration")
                        .HasColumnType("text");

                    b.Property<string>("AircraftType")
                        .HasColumnType("text");

                    b.Property<string>("AircraftTypeIATACode")
                        .HasColumnType("text");

                    b.Property<int>("SeatMapId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AircraftRegistration")
                        .IsUnique();

                    b.HasIndex("SeatMapId")
                        .IsUnique();

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.ClassConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfRows")
                        .HasColumnType("integer");

                    b.Property<int>("SeatPositionsAvailable")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("ClassConfigurations");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Codeshare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodeshareAirlineId")
                        .HasColumnType("integer");

                    b.Property<int>("CodeshareFlightNumber")
                        .HasColumnType("integer");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodeshareAirlineId");

                    b.HasIndex("FlightId");

                    b.ToTable("Codeshares");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirportName")
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("IATAAirportCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightBaggage", b =>
                {
                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<int>("BaggageId")
                        .HasColumnType("integer");

                    b.HasKey("FlightId", "BaggageId");

                    b.HasIndex("BaggageId");

                    b.ToTable("FlightBaggage");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.BookingReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PNR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PNR")
                        .IsUnique();

                    b.ToTable("BookingReferences");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMarkedAsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.FrequentFlyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("integer");

                    b.Property<string>("CardholderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrequentFlyerNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MilesAvailable")
                        .HasColumnType("bigint");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<string>("TierLever")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("FrequentFlyerNumber")
                        .IsUnique();

                    b.HasIndex("PassengerId")
                        .IsUnique();

                    b.ToTable("FrequentFlyers");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.SSRCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SSRCodes");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.SpecialServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FreeText")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsFreeTextMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("SSRCodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SSRCodeId");

                    b.ToTable("SpecialServiceRequests");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerComment", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.HasKey("PassengerId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("PassengerComment");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerFlight", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.HasKey("PassengerId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("PassengerFlight");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerSpecialServiceRequest", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialServiceRequestId")
                        .HasColumnType("integer");

                    b.HasKey("PassengerId", "SpecialServiceRequestId");

                    b.HasIndex("SpecialServiceRequestId");

                    b.ToTable("PassengerSpecialServiceRequest");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BoardingSequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FrequentFlyerId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PNRId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PNRId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Core.PassengerContext.Regulatory.APISData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateOfIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IssueCountryId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NationalityId")
                        .HasColumnType("integer");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("IssueCountryId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("PassengerId");

                    b.ToTable("APISData");
                });

            modelBuilder.Entity("Core.PassengerContext.Regulatory.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country2LetterCode")
                        .HasColumnType("text");

                    b.Property<string>("Country3LetterCode")
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Core.PassengerContext.Regulatory.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Core.SeatingContext.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardingZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChargeable")
                        .HasColumnType("boolean");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<char>("Position")
                        .HasColumnType("character(1)");

                    b.Property<byte>("Row")
                        .HasColumnType("smallint");

                    b.Property<int>("SeatMapId")
                        .HasColumnType("integer");

                    b.Property<string>("SeatStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SeatMapId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Core.SeatingContext.SeatMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SeatMaps");
                });

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("PassengerCheckedBags")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.BaggageContext.SpecialBag", "SpecialBag")
                        .WithMany()
                        .HasForeignKey("SpecialBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.BaggageContext.TagNumber", "TagNumber")
                        .WithOne("Baggage")
                        .HasForeignKey("Core.BaggageContext.Baggage", "TagNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("SpecialBag");

                    b.Navigation("TagNumber");
                });

            modelBuilder.Entity("Core.BoardingContext.Boarding", b =>
                {
                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithOne("Boarding")
                        .HasForeignKey("Core.BoardingContext.Boarding", "FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.FlightInfo.Destination", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.HasOne("Core.SeatingContext.SeatMap", "SeatMap")
                        .WithOne("Aircraft")
                        .HasForeignKey("Core.FlightContext.FlightInfo.Aircraft", "SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.ClassConfiguration", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Aircraft", "Aircraft")
                        .WithMany("ClassConfigurations")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Codeshare", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "CodeshareAirline")
                        .WithMany()
                        .HasForeignKey("CodeshareAirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("Codeshare")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeshareAirline");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Destination", b =>
                {
                    b.HasOne("Core.PassengerContext.Regulatory.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Core.FlightContext.JoinClasses.FlightBaggage", b =>
                {
                    b.HasOne("Core.BaggageContext.Baggage", "Baggage")
                        .WithMany("Flights")
                        .HasForeignKey("BaggageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("TotalCheckedBags")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baggage");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.FrequentFlyer", b =>
                {
                    b.HasOne("Core.FlightContext.FlightInfo.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithOne("FrequentFlyer")
                        .HasForeignKey("Core.PassengerContext.Booking.FrequentFlyer", "PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.SpecialServiceRequest", b =>
                {
                    b.HasOne("Core.PassengerContext.Booking.SSRCode", "SSRCode")
                        .WithMany()
                        .HasForeignKey("SSRCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SSRCode");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerComment", b =>
                {
                    b.HasOne("Core.PassengerContext.Booking.Comment", "Comment")
                        .WithMany("PaxWithComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("Comments")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerFlight", b =>
                {
                    b.HasOne("Core.FlightContext.Flight", "Flight")
                        .WithMany("TotalBookedPax")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("Flights")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.PassengerContext.JoinClasses.PassengerSpecialServiceRequest", b =>
                {
                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("SSRList")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Booking.SpecialServiceRequest", "SpecialServiceRequest")
                        .WithMany()
                        .HasForeignKey("SpecialServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("SpecialServiceRequest");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.HasOne("Core.PassengerContext.Booking.BookingReference", "PNR")
                        .WithMany("LinkedPassengers")
                        .HasForeignKey("PNRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PNR");
                });

            modelBuilder.Entity("Core.PassengerContext.Regulatory.APISData", b =>
                {
                    b.HasOne("Core.PassengerContext.Regulatory.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Regulatory.Country", "IssueCountry")
                        .WithMany()
                        .HasForeignKey("IssueCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Regulatory.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("IssueCountry");

                    b.Navigation("Nationality");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Core.SeatingContext.Seat", b =>
                {
                    b.HasOne("Core.PassengerContext.Passenger", "Passenger")
                        .WithMany("SeatAssignments")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.SeatingContext.SeatMap", "SeatMap")
                        .WithMany("Seats")
                        .HasForeignKey("SeatMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("SeatMap");
                });

            modelBuilder.Entity("Core.BaggageContext.Baggage", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Core.BaggageContext.TagNumber", b =>
                {
                    b.Navigation("Baggage")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.FlightContext.Flight", b =>
                {
                    b.Navigation("Boarding")
                        .IsRequired();

                    b.Navigation("Codeshare");

                    b.Navigation("TotalBookedPax");

                    b.Navigation("TotalCheckedBags");
                });

            modelBuilder.Entity("Core.FlightContext.FlightInfo.Aircraft", b =>
                {
                    b.Navigation("ClassConfigurations");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.BookingReference", b =>
                {
                    b.Navigation("LinkedPassengers");
                });

            modelBuilder.Entity("Core.PassengerContext.Booking.Comment", b =>
                {
                    b.Navigation("PaxWithComments");
                });

            modelBuilder.Entity("Core.PassengerContext.Passenger", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Flights");

                    b.Navigation("FrequentFlyer");

                    b.Navigation("PassengerCheckedBags");

                    b.Navigation("SSRList");

                    b.Navigation("SeatAssignments");

                    b.Navigation("TravelDocuments");
                });

            modelBuilder.Entity("Core.SeatingContext.SeatMap", b =>
                {
                    b.Navigation("Aircraft");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
